name: Get data from PDF file

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # At 00:00 on day-of-month 1

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Installing dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"
      - name: Running script
        run: python fetch.py
        env:
          SPECIAL_OPENAI_KEY: ${{ secrets.SPECIAL_OPENAI_KEY }}
      - name: Commit and push changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push